name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the project sources 
      run: ./gradlew build
    - name: Build the Docker image
      run: docker build -f src/main/docker/Dockerfile.jvm -t idrams56/quarkus-tasks .
    - name: Pulbisher the Docker image
      run: docker push idrams56/quarkus-tasks
