name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '13' 
    - name: Build the project sources 
      run: ./gradlew build
    - name: Build the Docker image
      run: docker build -f src/main/docker/Dockerfile.jvm . -t idrams56/quarkus-tasks
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: idrams56/quarkus-tasks
        tag_with_ref: true
